name: Auto Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  upgrade-deps:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js Version 20 (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm@v9
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install & Upgrade Dependencies
        run: |
          pnpm install
          npm run upgrade
          pnpm install --lockfile-only

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          github-token: ${{ secrets.BOT_TOKEN }}
          branch: "update-dependencies"
          base: "master"
          labels: |
            hamster
            bot
            dependencies
            automated
            pull-request
          reviewers: offensive-vk
          commit-message: "Update Dependencies - package.json"
          title: "Upgrade Dependencies To Latest - Automated"
          body: |
            ## Updated all Dependencies to Latest Versions.

            > [!IMPORTANT]
            > This PR Updates the Dependencies to the Latest Versions.
            >

            - Author: @TheHamsterBot
            - Branch: ${{ github.base_ref }} (base) / ${{ github.head_ref }} (head)
            - Commit: ${{ github.sha }}
            - Workflow Path: ${{ github.workflow_ref }}
            - Pull Request Number: #${{ github.event.number }}
            - Pull Request Title: ${{ github.event.pull_request.title }}
            - Current Action Status: ${{ github.action_status }}

            **Please Review the Changes and Merge the PR if everything is fine.**
