name: CI Build Project 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '50 23 * * *' # Everyday at 11:50 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Install dependencies and run npm script
      run: |
        npm install
        npm run build
        echo Build Successful.
