name: Node.js CI - Matrix

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}  # Run on different operating systems

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Matrix for different OS
        node-version: [16.x, 18.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
